### ISSUE TITLE
Also trying to catch a cat

### ISSUE THREAD

**Issue by prachetasp** [ebahsini/catch-a-cat#1]
Hello

I am also trying to catch a cat, but unfortunately your repository is very unhelpful in this regard. Can you please provide some example code indicating how I may catch a cat?

Thanks

**Comment by ebahsini** [comment]
Hello

I'm sorry, I actually caught the cat. As of now I can neither confirm, nor deny, that this is my cat; and not yours.

Until I have proper ownership filters in place I regret to inform you that this repo will stay empty. It's just not safe for the public.

Welcome
